DROP TABLE IF EXISTS BATCH;
CREATE TABLE IF NOT EXISTS BATCH (BATCH_ID IDENTITY NOT NULL PRIMARY KEY, BREWFATHER_ID VARCHAR(255) NOT NULL, BATCH_NAME VARCHAR(255) NOT NULL, BATCH_NUMBER BIGINT NOT NULL, BATCH_DATE BIGINT NOT NULL, BATCH_STATUS VARCHAR(255) NOT NULL, BATCH_STYLE VARCHAR(255) NOT NULL);
CREATE UNIQUE INDEX BATCH_BREWFATHER_ID ON BATCH(BREWFATHER_ID);
