DROP TABLE IF EXISTS BATCH;
CREATE TABLE IF NOT EXISTS BATCH (id IDENTITY NOT NULL PRIMARY KEY, BREWFATHER_ID VARCHAR(255) NOT NULL, NAME VARCHAR(255) NOT NULL, BATCH_NUMBER BIGINT NOT NULL, BATCH_DATE BIGINT NOT NULL, STATUS VARCHAR(255) NOT NULL, STYLE VARCHAR(255) NOT NULL);
CREATE UNIQUE INDEX BATCH_BREWFATHER_ID ON BATCH(BREWFATHER_ID);
